### PR TITLE
Added template D to struct Requests implementation

### PR DESCRIPTION
**Pull request by TileHalo**
Added template to Request, so it can be used with session.

### CODE REVIEW

**Comment by Ryman** [comment]
@TileHalo mind updating the commit message to `feat(*): allow usage with generic Request`?

**Comment by cburgdorf** [comment]
sidenote: `feat: allow usage with generic Request` would do be the equivalent but saves some chars.

**Comment by Ryman** [comment]
I was wondering if that was supported :P (landed https://github.com/nickel-org/nickel-postgres/commit/9d150516a9eabb85eeb61848b09e7dfe04627075 and thought I'd probably have to edit clog to get it parsing the title, glad I won't have to!)

**Comment by TileHalo** [comment]
Message changed, sorry about previous message.

**Comment by Ryman** [comment]
@TileHalo Thanks!

**Pull request merged**
