### PR TITLE
fix crate to work with latest r2d2 and r2d2_postgres

### PR DESCRIPTION
**Pull request by filsmick**

### CODE REVIEW

**Comment by Ryman** [comment]
First commit looks good but I'm unsure about the 2nd, running locally with `features = ["openssl"]` for `postgres` works fine for me? (with the type errors fixed)

I don't see any relation to the bug mentioned in the commit message. Have I missed something?

**Comment by filsmick** [comment]
@Ryman rust-postgres has a [cargo feature to conditionally compile ssl-related code](https://github.com/sfackler/rust-postgres/blob/8058bd323f606a30ff622b2992a528c7b58add0c/src/io/mod.rs#L21-L22), so that people who don't need Ssl can still use the crate without linking to the openssl system libraries.

Keeping the example as it was before updates broke the crate requires enabling this feature in the dependencies, thereby forcing users to build openssl even if they aren't going to use it. The obvious solution to let us have an example with SSL without forcing it upon library users would have been to use the `dev-dependencies` table in the .toml so that rust-postgres would be compiled with the openssl feature when testing, and without when using this crate from another one. However, as you can see in the issue I linked, this is buggy and users may still end up linking to openssl. Hence, the safest solution is not to use SSL in the example. The separate field for postgres isn't actually necessary, it can be listed as other dependencies - it's the remains of the tests I conducted locally. Fixing it now.

**Comment by Ryman** [comment]
Thanks for the outline, I finally see the forest! 

In future, we should reshape the api a bit so if ssl isn't even enabled then the api wouldn't ask for it, we'll be landing some changes to nickel itself soon which might affect this Middleware so I might handle that then.

For now, can you rebase to reword the commit messages to align with [this convention](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md) and to squash the last commit too.

**Comment by filsmick** [comment]
Is there anything preventing this PR from being merged?

**Comment by Ryman** [comment]
@filsmick Sorry, there's no notification when commits on a PR are changed so I didn't notice you'd updated this! Your changes LGTM.

**Pull request merged**
